# Generated by Django 4.2.7 on 2023-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ventasmqtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cemento', models.CharField(max_length=255)),
                ('arena', models.CharField(max_length=255)),
                ('grava', models.CharField(max_length=255)),
                ('aditivo', models.CharField(max_length=255)),
            ],
        ),
    ]
