# Generated by Django 4.2.7 on 2023-12-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasmqtt',
            name='placa',
            field=models.CharField(default='valor_predeterminado', max_length=255),
        ),
    ]
