# Generated by Django 4.2.7 on 2023-12-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ventasmqtt_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmasmqtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ViolacionActuador', models.CharField(max_length=255)),
                ('ParoDeEmergencia', models.CharField(max_length=255)),
                ('Presencia', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
