# Generated by Django 4.2.7 on 2023-12-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alarmasmqtt'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmasmqtt',
            name='ModoOperacion',
            field=models.CharField(default='valor_predeterminado', max_length=255),
        ),
    ]
