# Generated by Django 4.2.7 on 2023-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alarmasmqtt_modooperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor1mqtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor1', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='alarmasmqtt',
            old_name='ParoDeEmergencia',
            new_name='Alarma',
        ),
        migrations.RemoveField(
            model_name='alarmasmqtt',
            name='ModoOperacion',
        ),
        migrations.RemoveField(
            model_name='alarmasmqtt',
            name='Presencia',
        ),
        migrations.RemoveField(
            model_name='alarmasmqtt',
            name='ViolacionActuador',
        ),
    ]
