# Generated by Django 4.2.7 on 2023-12-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sensor1mqtt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor1mqtt',
            old_name='sensor1',
            new_name='sensor',
        ),
    ]
